### ISSUE TITLE
AppSync submit mutations with big delays

### ISSUE THREAD

**Issue by andrey-chorniy** [awslabs/aws-mobile-appsync-sdk-android#203]
Our application uses AWSAppSyncClient and enqueues mutations to push data to the server

On one of the installatons, mutations are successfully enqueued to the AppSync (on the device, so they are saved to AppSync DB) but synced to the AppSync backend with huge delays (40 - 120 minutes or even more)
Please note that each (40-120) minutes app send **only one mutation** and the next one is sent after another big delay.

As a result at this point, app submit events generated and saved on July 12 only now (on July 17).
We do not see exceptions in the log. We do see that AppSync backend process that requests without issues, so we assume (and we could see it in the logs) that delays created on the client.
Other users of the app do not experience such issues - their data is synced without delays.

In the same time, we have another AppSyncClient with different credentials-provider - it submits much more mutations without delays.

How can we identify the reasons of this problem? (we have access to logcat logs on this device, but can't debug on it)
Is there any way to fix/avoid such problems?

**Technical Details**
The mutation was enqueued in AppSync and our custom  interceptor logged it

> 2019-07-12 00:54:50.112 +0300 EEST I ApolloClientInterceptor  Logcat:0 logcat   Associating mutation ce44fde1-bd14-46a0-9f62-f6589ce84b0d_event with request id d02eb7bb-ace5-490d-9df4-ecbd5c1b745c

Long time after, AppSync started executing the mutation:

> 2019-07-12 01:36:19.986 +0300 EEST I InterceptorCallback  Logcat:0 logcat   Thread:[113691]: onResponse()
> 2019-07-12 01:31:32.884 +0300 EEST I InMemoryOfflineMutationManager  Logcat:0 logcat   Thread:[113688]:Executing mutation [d02eb7bb-ace5-490d-9df4-ecbd5c1b745c]
In about 5 seconds after that the mutation was successfully stored (we found appropriate record in DynamoDB table)

However (and that's the problem), the logs show that mutation was removed from offline persistence manager only in 5 minutes. That locked the execution of other mutations during this time.

> 2019-07-12 01:36:19.986 +0300 EEST I InterceptorCallback  Logcat:0 logcat   Thread:[113691]: onResponse()
> 2019-07-12 01:36:19.99 +0300 EEST I AppSyncSaveOps  Logcat:0 logcat   Mutation CreateEvent succeeded, op id: e2a576553fe1701a0d369481b42d81ded046f9705537301991e1f8168d481e4d, input
> 2019-07-12 01:36:21.069 +0300 EEST I PersistentOfflineMutationManager  Logcat:0 logcat   Thread:[113691]:Removing mutation [d02eb7bb-ace5-490d-9df4-ecbd5c1b745c] from persistent store.

**Expected behavior**
Minimal delays expected.

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.10.0

**Device Information (please complete the following information):**
 - Device: Samsung Galaxy S8+
 - Android Version: 9.0

**Additional context**
We have a custom ApolloInterceptor that we added using reflection this way (we hope it does not affect the issue, it work fine on our devices, but we think it worth to note we use it):
```
ApolloClient::class.java.getDeclaredField("applicationInterceptors")
.also { it.isAccessible = true}.get(appSyncClient.mApolloClient) as MutableList<ApolloInterceptor>)
                .add(0, ApolloClientInterceptor)
```

Here is how our custom ApolloInterceptor is written:
```
object ApolloClientInterceptor: ApolloInterceptor {
    override fun interceptAsync(request: ApolloInterceptor.InterceptorRequest, chain: ApolloInterceptorChain, dispatcher: Executor, callBack: ApolloInterceptor.CallBack) {
        if (request.operation !is Mutation<*, *, *>) {
            //Not a mutation. Nothing to do here - move on to the next link in the chain.
            chain.proceedAsync(request, dispatcher, callBack)
            return
        }
        doSomeLocalOpsInDb(request)
        chain.proceedAsync(request, dispatcher, callBack)
    }

    override fun dispose() {
    }
}
```

**Comment by palpatim** [comment]
@andrey-chorniy Thanks for reporting this issue. We'll investigate and update when we have some insight.

In the meantime, as @nchorniy referenced on #204, is there any particular difference in the state of the queues between the devices exhibiting different behavior? For example, does the "slow mutations" device have a large number of mutations in the queue, while the other device does not?

**Comment by andrey-chorniy** [comment]
We estimate the max-size of unsynced mutations in his queue as 1440 on this moment (it for sure can be less)
App generates about ~290 (up to 300) events (mutations) per day

We have two different app-sync clients in the app (another AppSyncClient has different credentials provider) and we submit more than 300 mutations per-day through it (400 - 600 or even more). In either case - that other AppSyncClient does not have such issues.

**Updates** User has upgraded the app recently (a half hour ago) and we've found that mutations pushed to the server with much bigger rate. This update does not include anything related to the AppSync, so no code updates were here. What may affect it - is that AppSyncClient has been re-created, app-process were killed.
Right now we see that device is pushing data from the past with a rate ~10-20 mutations per 5 seconds

**Comment by nchorniy** [comment]
**Update**

Based on observations of the AppSync behavior on this device we think that the following could happen:
1. Starting more than a month ago, due to failure to get AWS credentials (`AWSMobileClient.getCredentials()`) AppSync has stored a lot of records in local database
1. Our custom setting of `mutationQueueExecutionTimeout` was `Long.MAX_VALUE / 2` (which was done to meet the requirement of preventing data loss) and because of that mutations were not dropped from db
1. When the app upgraded together with AppSync and aws-sdk-android, the credentials problem was automatically resolved and after that:
1. AppSync started syncing thousands of stored records against `PersistentOfflineMutationManager.processNextMutationObject()` one by one
1. it went well for some time
1. However (and that's our assumption), in about 30-40 minutes of such instant load android system could do one or both of the following:
   1. degrade ability of `ThreadPoolExecutor` created inside `AppSyncCustomNetworkInvoker` to produce new threads (we could hardly believe that could happen)
    1. degrade priority, e.g. CPU resources allocated for the thread(s) created by `AppSyncCustomNetworkInvoker.dispatcher` (there is probably just one thread created)

We think that could be the case because, as was pointed before, the records created in result of Mutation execution appeared in DynamoDB 5 minutes before android device logged the line about successful mutation execution and its removal:
```
2019-07-12 01:31:32.884 +0300 EEST I InMemoryOfflineMutationManager Logcat:0 logcat Thread:[113688]:Executing mutation [d02eb7bb-ace5-490d-9df4-ecbd5c1b745c]
```

5 mins later
```
2019-07-12 01:36:19.986 +0300 EEST I InterceptorCallback Logcat:0 logcat Thread:[113691]: onResponse()
2019-07-12 01:36:19.99 +0300 EEST I AppSyncSaveOps Logcat:0 logcat Mutation CreateEvent succeeded, op id: e2a576553fe1701a0d369481b42d81ded046f9705537301991e1f8168d481e4d, input
2019-07-12 01:36:21.069 +0300 EEST I PersistentOfflineMutationManager Logcat:0 logcat Thread:[113691]:Removing mutation [d02eb7bb-ace5-490d-9df4-ecbd5c1b745c] from persistent store.
```

In that case, the record was stored in DynamoDB near `2019-07-12 01:31:36 +0300 EEST`, but not on `2019-07-12 01:36:19.986 +0300 EEST`.

**Comment by nchorniy** [comment]
**Update 2**
We identified a few new facts which we need to outline to check if they may affect this issue.
In the comment above we've described the issue - app was restarted and after that it successfully pushed records which were previously stored in appsync's local android db, however no data collected after reboot was synced. Let's name it a **Problem 2**.

We've noticed that we've created `AWSAppSyncClient` several times and it had read all mutations from local db in constructor of `PersistentOfflineMutationManager`

```
2019-07-18 21:53:52.038 +0300 EEST I PersistentOfflineMutationManager  Logcat:0 logcat   Thread:[2]:In Constructor
2019-07-18 21:53:52.448 +0300 EEST I PersistentOfflineMutationManager  Logcat:0 logcat   Thread:[664]:In Constructor (after aws initialize)
2019-07-18 21:53:55.468 +0300 EEST I PersistentOfflineMutationManager  Logcat:0 logcat   Thread:[698]:In Constructor (after token reanimation)
```

We've updated the code to ensure that `AWSAppSyncClient` would be created only once, so `PersistentOfflineMutationManager` in turn will also be created only once.
We made a release to see if it will solve the issue with the problematic device.

However, we would like to check with you if creation of multiple `AWSAppSyncClient` may cause the issues which we've outlined in this ticket.

As we've mentioned in the #204 `AWSAppSyncClient` creation makes request to DB and reads all records from it, so it may take a long time (seconds) to finish the `AWSAppSyncClient` creation (which probably was the reason in our case of parallel creation of it from different threads).

Another question we would like to ask is: "Is it normal practice to create `AWSAppSyncClient` several times?"
[In the example from doc](https://aws-amplify.github.io/docs/android/api#client-initialization) we see that it is created in the `Activity.onCreate()` so it will be created each time user opens the Activity. 

Also: in our case parallel creation of `AWSAppSyncClient` has led to the db access error. As we noted before - we've addressed this problem, so it should fix the **Problem 2**, but we are not sure it will also fix **Problem 1** which we described initially - AppSync pushes records with a huge delay between each record (1 - 2 - 3) hours.

```
2019-07-18 21:54:11.41 +0300 EEST W SQLiteLog  Logcat:0 logcat   (5) database is locked
2019-07-18 21:54:11.424 +0300 EEST W SQLiteDatabase  Logcat:0 logcat   Failed to open database '/data/user/0/com.ehawk.repath/databases/appsyncstore'.
2019-07-18 21:54:11.424 +0300 EEST W SQLiteDatabase  Logcat:0 logcat   	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:893)
2019-07-18 21:54:11.424 +0300 EEST W SQLiteDatabase  Logcat:0 logcat   	at com.apollographql.apollo.cache.normalized.sql.SqlNormalizedCache.<init>(SqlNormalizedCache.java:69)
2019-07-18 21:54:11.424 +0300 EEST W SQLiteDatabase  Logcat:0 logcat   	at com.amazonaws.mobileconnectors.appsync.AppSyncService.createInstance(AppSyncService.kt:79)
2019-07-18 21:54:11.424 +0300 EEST W SQLiteDatabase  Logcat:0 logcat   	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:460)
...
2019-07-18 21:54:11.424 +0300 EEST W SQLiteDatabase  Logcat:0 logcat   	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1229)
2019-07-18 21:54:11.424 +0300 EEST W SQLiteDatabase  Logcat:0 logcat   	at com.amazonaws.mobileconnectors.appsync.AppSyncService.authenticatedInstance(AppSyncService.kt:53)
2019-07-18 21:54:11.424 +0300 EEST W SQLiteDatabase  Logcat:0 logcat   android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY[5]): , while compiling: PRAGMA journal_mode
2019-07-18 21:54:11.424 +0300 EEST W SQLiteDatabase  Logcat:0 logcat   	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:490)
2019-07-18 21:54:11.424 +0300 EEST W SQLiteDatabase  Logcat:0 logcat   	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1292)
...
2019-07-18 21:54:11.424 +0300 EEST W SQLiteDatabase  Logcat:0 logcat   	at com.apollographql.apollo.cache.normalized.sql.SqlNormalizedCacheFactory.create(SqlNormalizedCacheFactory.java:16)
2019-07-18 21:54:11.424 +0300 EEST W SQLiteDatabase  Logcat:0 logcat   	at com.apollographql.apollo.cache.normalized.NormalizedCacheFactory.createChain(NormalizedCacheFactory.java:44)
2019-07-18 21:54:11.424 +0300 EEST W SQLiteDatabase  Logcat:0 logcat   	at com.apollographql.apollo.ApolloClient$Builder.build(ApolloClient.java:473)
2019-07-18 21:54:11.424 +0300 EEST W SQLiteDatabase  Logcat:0 logcat   	at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient.<init>(AWSAppSyncClient.java:249)
2019-07-18 21:54:11.424 +0300 EEST W SQLiteDatabase  Logcat:0 logcat   	at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient.<init>(AWSAppSyncClient.java:68)
2019-07-18 21:54:11.424 +0300 EEST W SQLiteDatabase  Logcat:0 logcat   	at com.ehawk.common.workers.ReanimateInvalidatedTokensWorker$doWork$1.invokeSuspend(ReanimateInvalidatedTokensWorker.kt:59)
```

**Comment by andrey-chorniy** [comment]
The device on which the problem is reproduced got our updated app with the following change: no multiple `AWSAppSyncClient` instances are created.
However, the problem still appears. And here is our other findings

- AppSync has synced a lot of records from persistence offline storage
- AppSync has also synced exactly one record queued after the app upgrade, however:
- although this one record appeared in our db, `QueueUpdateHandler.mutationInProgress` was never set to false according to the logs


Here is the records got queued to AppSync
```
2019-07-20 00:56:23.267 +0300 EEST I AppSyncOfflineMutationManager  Logcat:0 logcat   Thread:[9500]: Created both in-memory and persistent records. Now going to signal queue handler.
2019-07-20 00:56:23.267 +0300 EEST I AppSyncOfflineMutationManager  Logcat:0 logcat   Thread:[9403]:Persistent mutations queue is EMPTY!. Will check inMemory Queue next
2019-07-20 00:56:23.267 +0300 EEST I QueueUpdateHandler  Logcat:0 logcat   Thread:[9403]: Setting mutationInProgress as true.
2019-07-20 00:56:23.27 +0300 EEST I AppSyncOfflineMutationManager  Logcat:0 logcat   Thread:[9403]: Processing next from in Memory queue
2019-07-20 00:56:23.271 +0300 EEST I InMemoryOfflineMutationObject  Logcat:0 logcat   Thread:[9403]: Executing mutation by proceeding with the chain.
2019-07-20 00:56:23.271 +0300 EEST I AppSyncComplexObjectsInterceptor  Logcat:0 logcat   Thread:[9403]: No s3 Objects found. Proceeding with the chain
2019-07-20 00:56:23.271 +0300 EEST I S3ObjectManagerImplementation  Logcat:0 logcat   Thread:[9403]: Looking at Key [input] of type [CreateEventInput]
2019-07-20 00:56:23.271 +0300 EEST I InMemoryOfflineMutationManager  Logcat:0 logcat   Thread:[9403]:Executing mutation [efd218b5-90f5-43dc-a565-21caf5769087]
2019-07-20 00:56:23.275 +0300 EEST I InterceptorCallback  Logcat:0 logcat   Thread:[9505]: onFetch()
2019-07-20 00:56:23.278 +0300 EEST I RetryInterceptor  Logcat:0 logcat   Retry Interceptor called
2019-07-20 00:56:23.28 +0300 EEST I AppSyncSigV4SignerInterceptor  Logcat:0 logcat   Signer Interceptor called
```

The record was stored on the server at `2019-07-20 12:56:25 AM +0300 EEST`

However:
- further logs do not contain any mention about `efd218b5-90f5-43dc-a565-21caf5769087`
- till `2019-07-20 01:24:55.048 +0300 EEST` (where the logs end) we've got tens of messages in the logs Thread:[9403]: Got message to take action on the mutation queue. (note, that JVM process is not killed during this time)
- but there is no line [9403]: Got message to process next mutation if one exists. which means that *during 1.5 HOURS the mutation is considered in progress ?*
